### ISSUE TITLE
nativescript-braintree paypal not working in ios 

### ISSUE THREAD

**Issue by lettertoamit** [jibon57/nativescript-braintree#21]
nativescript-braintree paypal not working in ios  after a popup appear. it shows select "paypal"/"creditcard"  , when i select credit card things works fine but if i select "paypal" no redirection  work. My android works fine but when it comes to ios .paypal redirect to website not working. Kindly help .

**Comment by jibon57** [comment]
You haven't followed this: https://github.com/jibon57/nativescript-braintree#setup-ios-paypal--venmo

**Comment by jibon57** [comment]
> This scheme must start with your app's Bundle ID and be dedicated to Braintree app switch returns. For example, if the app bundle ID is com.yourcompany.yourapp, then your URL scheme could be com.yourcompany.yourapp.payments or com.yourcompany.yourapp.anything. Above I used org.nativescript.demo.payments because app's bundle ID is org.nativescript.demo & we will need this value below.

**Comment by jibon57** [comment]
@lettertoamit you are overriding `UIApplicationDelegate` with your custom `delegate` that's why it isn't working. You can have a look here what I have did:

https://github.com/jibon57/nativescript-braintree/blob/a7c296d203c3bf6f187926079334860b64096135/src/getappdelegate.ts#L56

https://github.com/jibon57/nativescript-braintree/blob/a7c296d203c3bf6f187926079334860b64096135/src/braintree.ios.ts#L8

So, you can also do something like that one for calling `initAnalytics()`

**Comment by lettertoamit** [comment]
i removed analytics code but it is still not working

**Comment by lettertoamit** [comment]
hi there thanks for help , I think i removed  info.plist the  CFBundleURLTypes key and array and add it to another CFBundleURLTypes present , really thnks for help
